font_size: 22 # specify font size
theme: ferns 
tree_0:
  general:
    reddit: "https://www.reddit.com/"
    github: "https://www.github.com/"
    homepage: "https://www.alexanderweichart.de"
  video:
    youtube: "https://www.youtube.com/"
    twitch: "https://www.twitch.com/"
  music:
    soundcloud: "https://soundcloud.com/discover"
tree_1:
  uni:
    spur: "https://spur.uni-regensburg.de/"
    grips: "https://elearning.uni-regensburg.de/"
    flexNow: "https://fn2.uni-regensburg.de/FN2AUTH/login.jsp"
  resources:
    oReilly: "https://learning.oreilly.com/home/"
tree_2:
  work:
    kanban: "https://tools.mi.ur.de/kanboard/board/3"
    hours: "https://wiki.mi.ur.de/orga/shk/alexanderweichart"
    gather: "https://gather.town/app/nUozY38QLGD3Ziqv/pda"
    homepage: "https://hci.ur.de"

